Repository brain-tec/e-commerce, pull requests merged in 2022-08, with the labels that each got.

#440 15.0 mig website sale require login
  setup/website_sale_require_login/odoo/addons/website_sale_require_login
  setup/website_sale_require_login/setup.py
  website_sale_require_login/README.rst
  website_sale_require_login/__init__.py
  website_sale_require_login/__manifest__.py
  website_sale_require_login/controllers/__init__.py
  website_sale_require_login/controllers/main.py
  website_sale_require_login/hooks.py
  website_sale_require_login/i18n/ca.po
  website_sale_require_login/i18n/de.po
  website_sale_require_login/i18n/es.po
  website_sale_require_login/i18n/it.po
  website_sale_require_login/i18n/sl.po
  website_sale_require_login/i18n/website_sale_require_login.pot
  website_sale_require_login/readme/CONFIGURE.rst
  website_sale_require_login/readme/CONTRIBUTORS.rst
  website_sale_require_login/readme/DESCRIPTION.rst
  website_sale_require_login/readme/USAGE.rst
  website_sale_require_login/static/description/icon.png
  website_sale_require_login/static/description/index.html
  website_sale_require_login/static/tests/tours/checkout.js
  website_sale_require_login/tests/__init__.py
  website_sale_require_login/tests/test_checkout.py
  website_sale_require_login/views/website_sale.xml
Labels: odoo_migration, 15.0.project_mi_465

#441 Syncing from upstream OCA/e-commerce (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/website_sale_require_login/odoo/addons/website_sale_require_login
  setup/website_sale_require_login/setup.py
  website_sale_require_login/README.rst
  website_sale_require_login/__init__.py
  website_sale_require_login/__manifest__.py
  website_sale_require_login/controllers/__init__.py
  website_sale_require_login/controllers/main.py
  website_sale_require_login/hooks.py
  website_sale_require_login/i18n/ca.po
  website_sale_require_login/i18n/de.po
  website_sale_require_login/i18n/es.po
  website_sale_require_login/i18n/it.po
  website_sale_require_login/i18n/sl.po
  website_sale_require_login/i18n/website_sale_require_login.pot
  website_sale_require_login/readme/CONFIGURE.rst
  website_sale_require_login/readme/CONTRIBUTORS.rst
  website_sale_require_login/readme/DESCRIPTION.rst
  website_sale_require_login/readme/USAGE.rst
  website_sale_require_login/static/description/icon.png
  website_sale_require_login/static/description/index.html
  website_sale_require_login/static/tests/tours/checkout.js
  website_sale_require_login/tests/__init__.py
  website_sale_require_login/tests/test_checkout.py
  website_sale_require_login/views/website_sale.xml
Labels: 15.0

#442 Syncing from upstream OCA/e-commerce (15.0)
  website_sale_require_login/i18n/ca.po
  website_sale_require_login/i18n/de.po
  website_sale_require_login/i18n/es.po
Labels: 15.0

#443 Syncing from upstream OCA/e-commerce (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/website_sale_comparison_hide_price/odoo/addons/website_sale_comparison_hide_price
  setup/website_sale_comparison_hide_price/setup.py
  website_sale_comparison_hide_price/README.rst
  website_sale_comparison_hide_price/__init__.py
  website_sale_comparison_hide_price/__manifest__.py
  website_sale_comparison_hide_price/i18n/website_sale_comparison_hide_price.pot
  website_sale_comparison_hide_price/readme/CONTRIBUTORS.rst
  website_sale_comparison_hide_price/readme/DESCRIPTION.rst
  website_sale_comparison_hide_price/static/description/icon.png
  website_sale_comparison_hide_price/static/description/index.html
Labels: 15.0

#444 Syncing from upstream OCA/e-commerce (14.0)
  website_sale_product_minimal_price/i18n/pt.po
Labels: 14.0

#445 Syncing from upstream OCA/e-commerce (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/website_sale_checkout_country_vat/odoo/addons/website_sale_checkout_country_vat
  setup/website_sale_checkout_country_vat/setup.py
  website_sale_checkout_country_vat/README.rst
  website_sale_checkout_country_vat/__init__.py
  website_sale_checkout_country_vat/__manifest__.py
  website_sale_checkout_country_vat/i18n/ca.po
  website_sale_checkout_country_vat/i18n/es.po
  website_sale_checkout_country_vat/i18n/fr.po
  website_sale_checkout_country_vat/i18n/website_sale_checkout_country_vat.pot
  website_sale_checkout_country_vat/readme/CONFIGURE.rst
  website_sale_checkout_country_vat/readme/CONTRIBUTORS.rst
  website_sale_checkout_country_vat/readme/DESCRIPTION.rst
  website_sale_checkout_country_vat/readme/USAGE.rst
  website_sale_checkout_country_vat/static/description/icon.png
  website_sale_checkout_country_vat/static/description/index.html
  website_sale_checkout_country_vat/static/src/js/dropdown.js
  website_sale_checkout_country_vat/views/templates.xml
Labels: 15.0

#446 Syncing from upstream OCA/e-commerce (13.0)
  README.md
  website_sale_stock_list_preview/__manifest__.py
  website_sale_stock_list_preview/controllers/main.py
Labels: 13.0
